//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketMachineCore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candle
    {
        public int CandleId { get; set; }
        public int MarketId { get; set; }
        public int PeriodId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal High { get; set; }
        public decimal Low { get; set; }
        public decimal Open { get; set; }
        public decimal Close { get; set; }
        public int Volume { get; set; }
    
        public virtual Market Market { get; set; }
    }
}
