//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketMachineCore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketType
    {
        public MarketType()
        {
            this.Markets = new HashSet<Market>();
        }
    
        public int MarketTypeId { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<Market> Markets { get; set; }
    }
}
